### ISSUE TITLE
Fix error

### ISSUE THREAD

**Issue by julikaiba** [Manawyrm/headsetcontrol-notificationd#5]
(somewhat "new" to working with public githubs so no clue if i could and should edit it myself)

Maybe I'm the only one, but for me the program stopped working recently. 
After looking through the code I noticed, that line 43
`$stateParse = explode(": ", $hscData[2]);`
needs to be changed to 
`$stateParse = explode(": ", $hscData[1]);`

As this is $hscData at that moment:

> Array
> (
>     [0] => Logitech G633/G635/G933/G935
>     [1] => Battery: Charging
>     [2] => Success!
>     [3] => 
> )

**Comment by Manawyrm** [comment]
> (somewhat "new" to working with public githubs so no clue if i could and should edit it myself)
Yes, you could! That's called a Pull Request. You can either do it by "forking" my repo, making changes and then creating a pull request, or you could just use the convenient "edit" button on top of every file in the web interface. This will do all required steps automatically for you. 

If you want to try it out, just go ahead and send a pull request with the changes. This also has the benefit of you being mentioned as the author/contributor of the change. 
If you don't want to, I'll gladly accept the change as is. Just tell me 😄 

I guess the output of headsetcontrol has changed slightly in the newer version, that's why the array has changed.

**Comment by julikaiba** [comment]
I tried a pull request, hope it worked 😆
